/* eslint-disable */
// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmergencyActiveRouteImport } from './routes/emergency-active'
import { Route as EmergencyWebViewRouteImport } from './routes/emergency-web-view'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as QrPassportRouteImport } from './routes/qr-passport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
})
const EmergencyActiveRoute = EmergencyActiveRouteImport.update({
  id: '/emergency-active',
  path: '/emergency-active',
  getParentRoute: () => rootRouteImport,
})
const EmergencyWebViewRoute = EmergencyWebViewRouteImport.update({
  id: '/emergency-web-view',
  path: '/emergency-web-view',
  getParentRoute: () => rootRouteImport,
})
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
})
const QrPassportRoute = QrPassportRouteImport.update({
  id: '/qr-passport',
  path: '/qr-passport',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmergencyActiveRoute: EmergencyActiveRoute,
  EmergencyWebViewRoute: EmergencyWebViewRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  QrPassportRoute: QrPassportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)